version: "3.3"
services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - backend-network
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
      JWT_SECRET: secret
      JWT_REFRESH_SECRET: secret

  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_GRAPHQL_API_URL: http://localhost:5000/graphql
      SKIP_PREFLIGHT_CHECK: true
    ports:
      - "3000:80"
    networks:
      - backend-network
    depends_on:
      - backend
      - database

networks:
  backend-network:
